# Generated by Django 3.2 on 2021-04-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=500)),
                ('item_dimensions', models.CharField(max_length=65)),
                ('item_weight', models.IntegerField()),
                ('item_category', models.CharField(choices=[('A', 'Appliances'), ('E', 'Electronics'), ('F', 'Furniture'), ('T', 'Tools')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('store_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('financial', models.CharField(max_length=250)),
                ('current_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.location'),
        ),
        migrations.CreateModel(
            name='Data_analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_id', models.CharField(max_length=128)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
